[project]
name = "feature_extraction_server-apis-legacy_api"
version = "0.1.0"
description = "Legacy API for FES."
authors = [
    {name = "Fynn Faber", email = "fynn.f.faber@proton.me"}
]
requires-python = ">=3.11"

[tool.flit.module]
name = "feature_extraction_server.services.legacy_api"

[build]
script = "flit build"
