[project]
name = "feature_extraction_server-models-tesseract"
version = "0.1.0"
description = "tesseract model for FES."
authors = [
    {name = "Fynn Faber", email = "fynn.f.faber@proton.me"}
]
requires-python = ">=3.11"

dependencies = [
    "pytesseract",
    "pillow"
]

[tool.flit.module]
name = "feature_extraction_server.models.tesseract"

[build]
script = "flit build"
