name: Build Docker Images

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch.
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # The type of runner that the job will run on.
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
      VERSION: "1.0" 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Checks-out your repository under $GITHUB_WORKSPACE
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Set in your repo's secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Set in your repo's secrets

    - name: Run build script
      run: |
        bash build_docker.sh
