name: Build Docker Images

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch.
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            PLUGINPATH=core:simple_plugin_manager:base_api:fastapi
            CMD_ENTRYPOINT="run-fes --port 8888 --host 0.0.0.0"
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/featureextractionserver:base-1.0
            ${{ secrets.DOCKER_USERNAME }}/featureextractionserver:base-latest

